export { default as AboutUs } from './AboutUs'
export { default as Gallery } from './Gallery'
export { default as Home } from './Home'
export { default as Events } from './Events'
export { default as ContactUs } from './ContactUs'
